local M = {}

---Define the plugin highlight groups for the current background.
function M.setup()
  local is_light = vim.o.background == 'light'

  if is_light then
    vim.api.nvim_set_hl(0, 'OmpBorder', { fg = '#9E9E9E', default = true })
    vim.api.nvim_set_hl(0, 'OmpBackground', { link = 'Normal', default = true })
    vim.api.nvim_set_hl(0, 'OmpSessionDescription', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'OmpMention', { link = 'Special', default = true })
    vim.api.nvim_set_hl(0, 'OmpToolBorder', { fg = '#B0BEC5', nocombine = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpMessageRoleAssistant', { link = 'Special', default = true })
    vim.api.nvim_set_hl(0, 'OmpMessageRoleUser', { link = 'Question', default = true })
    vim.api.nvim_set_hl(0, 'OmpDiffAdd', { bg = '#E8F5E8', default = true })
    vim.api.nvim_set_hl(0, 'OmpDiffDelete', { bg = '#FFEBEE', default = true })
    vim.api.nvim_set_hl(0, 'OmpDiffAddText', { link = 'Added', default = true })
    vim.api.nvim_set_hl(0, 'OmpDiffDeleteText', { link = 'Removed', default = true })
    vim.api.nvim_set_hl(0, 'OmpDiffGutter', { fg = '#757575', bg = '#F5F5F5', default = true })
    vim.api.nvim_set_hl(0, 'OmpDiffAddGutter', { fg = '#2E7D32', bg = '#F1FAF1', default = true })
    vim.api.nvim_set_hl(0, 'OmpDiffDeleteGutter', { fg = '#C62828', bg = '#FFF1F3', default = true })
    vim.api.nvim_set_hl(0, 'OmpPermissionBorder', { fg = '#FF9E3B', nocombine = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpContextualActions', { bg = '#90A4AE', fg = '#1976D2', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpInputLegend', { bg = '#757575', fg = '#424242', bold = false, default = true })
    vim.api.nvim_set_hl(0, 'OmpHint', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'OmpThinkingLevel', { link = '@attribute', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpGuardDenied', { fg = '#F44336', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpContextBar', { fg = '#3b4261', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextFile', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextCurrentFile', { link = 'OmpContext', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextCurrentFileNotUpdated', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextAgent', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextSelection', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextError', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextWarning', { link = 'DiagnosticWarn', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextInfo', { link = 'DiagnosticInfo', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextSwitchOn', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'OmpPickerTime', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'OmpDebugText', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'OmpReference', { fg = '#5F7896', default = true })
    vim.api.nvim_set_hl(0, 'OmpSymbolReference', { link = 'Identifier', default = true })
    vim.api.nvim_set_hl(0, 'OmpReasoningText', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'OmpPermissionTitle', { fg = '#FF9E3B', default = true })
    vim.api.nvim_set_hl(0, 'OmpDialogOptionHover', { bg = '#E3F2FD', fg = '#1976D2', default = true })
    vim.api.nvim_set_hl(0, 'OmpQuestionOption', { link = 'Normal', default = true })
    vim.api.nvim_set_hl(0, 'OmpQuestionBorder', { fg = '#E3F2FD', default = true })
    vim.api.nvim_set_hl(0, 'OmpQuestionTitle', { link = '@label', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpQuestionTabActive', { bg = '#E3F2FD', fg = '#1976D2', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpQuestionTabDone', { fg = '#2E7D32', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpQuestionTabPending', { fg = '#757575', default = true })
    vim.api.nvim_set_hl(0, 'OmpQuestionKeyHint', { fg = '#1976D2', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpChangedLines', { bg = '#FFF3BF', default = true })
  else
    vim.api.nvim_set_hl(0, 'OmpBorder', { fg = '#616161', default = true })
    vim.api.nvim_set_hl(0, 'OmpBackground', { link = 'Normal', default = true })
    vim.api.nvim_set_hl(0, 'OmpSessionDescription', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'OmpMention', { link = 'Special', default = true })
    vim.api.nvim_set_hl(0, 'OmpToolBorder', { fg = '#3b4261', nocombine = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpPermissionBorder', { fg = '#FF9E3B', nocombine = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpMessageRoleAssistant', { link = 'Added', default = true })
    vim.api.nvim_set_hl(0, 'OmpMessageRoleUser', { link = 'Question', default = true })
    vim.api.nvim_set_hl(0, 'OmpDiffAdd', { bg = '#2B3328', default = true })
    vim.api.nvim_set_hl(0, 'OmpDiffDelete', { bg = '#43242B', default = true })
    vim.api.nvim_set_hl(0, 'OmpDiffAddText', { link = 'Added', default = true })
    vim.api.nvim_set_hl(0, 'OmpDiffDeleteText', { link = 'Removed', default = true })
    vim.api.nvim_set_hl(0, 'OmpDiffGutter', { fg = '#6B7280', bg = '#252631', default = true })
    vim.api.nvim_set_hl(0, 'OmpDiffAddGutter', { fg = '#A5D6A7', bg = '#344032', default = true })
    vim.api.nvim_set_hl(0, 'OmpDiffDeleteGutter', { fg = '#EF9A9A', bg = '#52303A', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextualActions', { bg = '#3b4261', fg = '#61AFEF', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpInputLegend', { link = '@label', bold = false, default = true })
    vim.api.nvim_set_hl(0, 'OmpHint', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'OmpThinkingLevel', { link = '@attribute', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpGuardDenied', { fg = '#EF5350', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpContextBar', { fg = '#3b4261', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextFile', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextCurrentFile', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextCurrentFileNotUpdated', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextAgent', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextSelection', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextError', { link = 'DiagnosticError', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextWarning', { link = 'DiagnosticWarn', default = true })
    vim.api.nvim_set_hl(0, 'OmpContextSwitchOn', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'OmpPickerTime', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'OmpDebugText', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'OmpReference', { fg = '#8AA6C8', default = true })
    vim.api.nvim_set_hl(0, 'OmpSymbolReference', { link = 'Identifier', default = true })
    vim.api.nvim_set_hl(0, 'OmpReasoningText', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'OmpPermissionTitle', { fg = '#FF9E3B', default = true })
    vim.api.nvim_set_hl(0, 'OmpDialogOptionHover', { bg = '#2B3A5A', fg = '#61AFEF', default = true })
    vim.api.nvim_set_hl(0, 'OmpQuestionOption', { link = 'Normal', default = true })
    vim.api.nvim_set_hl(0, 'OmpQuestionBorder', { fg = '#2B3A5A', default = true })
    vim.api.nvim_set_hl(0, 'OmpQuestionTitle', { link = '@label', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpQuestionTabActive', { bg = '#2B3A5A', fg = '#61AFEF', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpQuestionTabDone', { fg = '#98C379', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpQuestionTabPending', { fg = '#7F8490', default = true })
    vim.api.nvim_set_hl(0, 'OmpQuestionKeyHint', { fg = '#61AFEF', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'OmpChangedLines', { bg = '#3D3520', default = true })
  end
end

return M
